[package]
name = "UIBoz-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/*",
    "crates/errors",
    "crates/style",
    "crates/renderer",
    "crates/frontend",
]

[dependencies]
itertools = "0.13.0"
dyn-clone = "1.0.17"

style = { path = "crates/style" }
errors = { path = "crates/errors" }
frontend = { path = "crates/frontend" }
renderer = { path = "crates/renderer" }
