[package]
name = "UIBoz-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
regex = "1.5"
itertools = "0.13.0"
jemallocator = "0.5.4"
dyn-clone = "1.0.17"
